### ISSUE TITLE
Many timeouts after API rewrite

### ISSUE THREAD

**Issue by ErikKalkoken** [zKillboard/RedisQ#20]
AA-Killtracker has been updated and is now also using the QueueID in all request.

However, we are seeing a lot of read timeouts with the new implementation of the RedisQ API. Some request are going through, but many run into the timeout. Some of my users are reporting they do not get any successful requests, just timeouts.

Example:
```
Traceback (most recent call last):
File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
R = retval = fun(*args, **kwargs)
File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
return self.run(*args, **kwargs)
File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/killtracker/tasks.py", line 53, in run_killtracker
killmail = Killmail.create_from_zkb_redisq()
File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/killtracker/core/killmails.py", line 411, in create_from_zkb_redisq
response = requests.get(
File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/requests/api.py", line 73, in get
return request("get", url, params=params, **kwargs)
File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/requests/api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
resp = self.send(prep, **send_kwargs)
File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
r = adapter.send(request, **kwargs)
File "/home/allianceserver/venv/auth/lib/python3.10/site-packages/requests/adapters.py", line 532, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='redisq.zkillboard.com', port=443): Read timed out. (read timeout=30)
```

**Comment by ErikKalkoken** [comment]
Here a current chart of these timeouts occurring over the last 24 hrs.

![Screenshot from 2023-11-24 18-25-07](https://github.com/zKillboard/RedisQ/assets/7696155/030c15ea-324b-4868-927e-337e971b7e38)

**Comment by cvweiss** [comment]
Earlier I identified an OS level issue with packets being dropped and have addressed it, hopefully, this prevents the timeouts from continuing.

**Comment by cvweiss** [comment]
@ErikKalkoken how are your charts looking?

**Comment by ErikKalkoken** [comment]
It looks good now. The timeout issue stopped occurring after yesterday around 20:00 UTC. Thanks a lot for your quick help!

![Screenshot from 2023-11-25 16-47-26](https://github.com/zKillboard/RedisQ/assets/7696155/4fe66a45-d320-42ad-b1e7-bb0b52949ba7)

**Comment by cvweiss** [comment]
Excellent, I'll mark the issue as closed.  Those new lines are likely from me bouncing the server while looking at another issue.
